# Generated by Django 5.0.1 on 2024-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PorteFeuilleClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=15)),
                ("owner_phone_number", models.CharField(max_length=15)),
                ("solde", models.IntegerField(default=0)),
            ],
        ),
    ]
