# Generated by Django 5.0.1 on 2024-01-22 08:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portefeuille", "0002_user_portefeuilleclient_owner_obj"),
    ]

    operations = [
        migrations.CreateModel(
            name="LumiClientRequeste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_benefitor", models.CharField(default="Nowa", max_length=15)),
                (
                    "date_requested",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2024, 1, 22, 8, 12, 13, 486059)
                    ),
                ),
                (
                    "date_approved",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 1, 22, 8, 12, 13, 486095)
                    ),
                ),
                (
                    "stage_progress",
                    models.IntegerField(
                        choices=[(1, "PENDING"), (2, "DONE")], default=1
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portefeuille.portefeuilleclient",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
