# Generated by Django 5.0.1 on 2024-01-23 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portefeuille", "0003_lumiclientrequeste_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lumiclientrequeste",
            name="owner_username",
            field=models.CharField(default="Noe", max_length=15),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 23, 4, 37, 23, 304214)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 23, 4, 37, 23, 304196)
            ),
        ),
    ]
