# Generated by Django 5.0.1 on 2024-01-23 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portefeuille", "0004_lumiclientrequeste_owner_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lumiclientrequeste",
            name="link_activate",
            field=models.URLField(default="http://127.0.0.1:8000/power/log/"),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 23, 10, 54, 29, 689182)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 23, 10, 54, 29, 689166)
            ),
        ),
    ]
