# Generated by Django 5.0.1 on 2024-01-24 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portefeuille", "0007_alter_lumiclientrequeste_date_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lumiclientrequeste",
            old_name="request_benefitor",
            new_name="creditor_phone_number",
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 9, 36, 20, 306870)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 9, 36, 20, 306833)
            ),
        ),
    ]
