# Generated by Django 5.0.1 on 2024-01-24 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portefeuille",
            "0008_rename_request_benefitor_lumiclientrequeste_creditor_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lumiclientrequeste",
            name="request_benefitor",
            field=models.CharField(default="Nowa", max_length=15),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="creditor_phone_number",
            field=models.CharField(default="61999222", max_length=15),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 9, 38, 5, 217789)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 9, 38, 5, 217752)
            ),
        ),
    ]
