# Generated by Django 5.0.1 on 2024-01-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portefeuille", "0009_lumiclientrequeste_request_benefitor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lumiclientrequeste",
            old_name="creditor_phone_number",
            new_name="benefitor_phone_number",
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 9, 51, 38, 902324)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 9, 51, 38, 902289)
            ),
        ),
    ]
