# Generated by Django 5.0.1 on 2024-01-24 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portefeuille",
            "0011_rename_amount_to_pay_lumiclientrequeste_amount_to_transact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 10, 29, 23, 733340)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 10, 29, 23, 733269)
            ),
        ),
    ]
