# Generated by Django 5.0.1 on 2024-01-24 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portefeuille", "0012_alter_lumiclientrequeste_date_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 10, 38, 4, 870392)
            ),
        ),
        migrations.AlterField(
            model_name="lumiclientrequeste",
            name="date_requested",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 10, 38, 4, 870373)
            ),
        ),
    ]
